### ISSUE TITLE
Not working the the newest version of create

### ISSUE THREAD

**Issue by MattDev-974** [Rabbitminers/Extended-Flywheels#35]
![Capture d'écran 2023-06-20 190142](https://github.com/Rabbitminers/Extended-Flywheels/assets/105660629/adf4bff8-e5da-4010-a50b-1c2560608061)

**Comment by SpottyTheTurtle** [comment]
neither have been updated to work with 0.5.1

**Comment by Tesver50** [comment]
next time pls give more information than just a screenshot, since you are probably french (guessed that from your user and the name of teh screenshot) and if you have some troubles in english i can help with that

**Comment by Attack8** [comment]
Extended Flywheels fixed by #36

**Comment by Tesver50** [comment]
it's not fixed right now
don't confuse github and updates
EF will be fixed once the next update comes out

**Comment by QianFuv** [comment]
> it's not fixed right now don't confuse github and updates EF will be fixed once the next update comes out

Can you give me an estimate of when the update will be compatible with version 0.5.1?

**Comment by SpottyTheTurtle** [comment]
When it's ready

**Comment by LadyKathleen** [comment]
I also have this issue with the flywheels.   I have been patiently waiting for a fix.
